# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d0938832e7d045e9ba9dd2e449810a0b06ae3706f4ff0973d4d7bbb0e6acbaf51da15262cb5cfdf7181ce0a4e22aba451a807303b2f6beb7070505228faaf7

test:
  secret_key_base: 4136fd981df3792018fe3980c1b4be132b61190c246f5e279f50eba96fe74ffc0ea2eda4f9b9332bacaa520f0348b76273a8909513343d284c28154386d14d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
